language: java
jdk: oraclejdk9

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean jacoco:prepare-agent install jacoco:report
after_success:
  - mvn coveralls:report
